layout_spectrum: 1
favicon: null
name: Madeleine Punde Photography
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
color:
  brandStrength: 0.4893617
  lightness: 0.2909376067109406
  saturation: 0.08708758791908622
  rhythmicContrast: 0.3288566947448999
  brandColors:
    - '#1E386E'
    - '#416DB5'
    - '#86B6F3'
    - '#FFB488'
    - '#774B76'
typography_spectrum: 0.1529643614776433
