name: Madeleine Punde Photography
favicon: null
layout_spectrum: 0.6553472869563848
typography_spectrum: 0.15296436147764325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11302490346133709
  lightness: 0.2909376067109406
  saturation: 0.08708758791908622
  rhythmicContrast: 0.32885669474489987
purpose: []
