layout_spectrum: 1
favicon: null
name: Madeleine Punde Photography
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.4893617
  lightness: 0.2909376067109406
  saturation: 0.08708758791908622
  rhythmicContrast: 0.3288566947448999
  brandColors:
    - '#546D9B'
    - '#394B78'
    - '#7791CF'
    - '#9ABDF3'
typography_spectrum: 0.1529643614776433
